language: node_js

node_js:
  - "10"

os:
  - linux
  - osx

env:
  matrix:
  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="10"

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - node --version
  - node -p 'process.platform + "@" + process.arch'
  - npm --version
  - npm install node-pre-gyp -g
  - npm install electron-builder -g
  - npm install npx -g

install:
  - npm install

script:
  - npm run electron:build
  - mkdir release
  
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

      cp dist_electron/*.deb release
      rename -v "s/linux/ubuntu/" release/*.deb
      cp dist_electron/*.deb release

      cp dist_electron/*.AppImage release
      rename -v "s/linux/ubuntu/" release/*.AppImage
      cp dist_electron/*.AppImage release

      cp dist_electron/*.snap release
      rename -v "s/linux/ubuntu/" release/*.snap
      cp dist_electron/*.snap release
    fi

  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cp dist_electron/*.dmg release
    fi

  - ls -lha release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libzmq-dev
      - libkrb5-dev
      - bc
      - bsdtar

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

deploy:
  - provider: releases
    file:
      - release/*.*
    file_glob: true
    skip_cleanup: true
    api_key: ${GITHUB_KEY}
    on:
      tags: true
